
  root: true
  parserOptions: 
    sourceType: 'module'
    ecmaVersion: 6
  env: 
    browser: true
    node: true
    es6: true
    commonjs: true
  plugins: [ "@typescript-eslint","prettier"]
  extends: [
    "prettier",
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended"
  ]
  parser: "@typescript-eslint/parser"
  rules:
    "linebreak-style": [2, "unix"]
    "no-extra-semi": 1
    "no-trailing-spaces": 2
    "eqeqeq": 2
    "no-var": 0